import dotenv from "dotenv"
import type {
	ChatCompletion,
	ChatCompletionMessageParam,
	ChatCompletionTool,
} from "openai/resources/index.mjs"
import { initDataset } from "braintrust"
import { isNil, omit, omitBy, pick } from "lodash"
import fs from "node:fs"
import path from "node:path"
import yargs from "yargs"
import { hideBin } from "yargs/helpers"

export interface Response {
	/**
	 * A list of fetched events
	 */
	events: {
		/**
		 * A unique identifier for the experiment event. If you don't provide one, BrainTrust will generate one for you
		 */
		id: string
		/**
		 * The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the experiment (see the `version` parameter)
		 */
		_xact_id: string
		/**
		 * The timestamp the experiment event was created
		 */
		created: string
		/**
		 * Unique identifier for the project that the experiment belongs under
		 */
		project_id: string
		/**
		 * Unique identifier for the experiment
		 */
		experiment_id: string
		/**
		 * The arguments that uniquely define a test case (an arbitrary, JSON serializable object). Later on, Braintrust will use the `input` to know whether two test cases are the same between experiments, so they should not contain experiment-specific state. A simple rule of thumb is that if you run the same experiment twice, the `input` should be identical
		 */
		input: unknown
		/**
		 * The output of your application, including post-processing (an arbitrary, JSON serializable object), that allows you to determine whether the result is correct or not. For example, in an app that generates SQL queries, the `output` should be the _result_ of the SQL query generated by the model, not the query itself, because there may be multiple valid queries that answer a single question
		 */
		output?: {
			[k: string]: unknown
		}
		/**
		 * The ground truth value (an arbitrary, JSON serializable object) that you'd compare to `output` to determine if your `output` value is correct or not. Braintrust currently does not compare `output` to `expected` for you, since there are so many different ways to do that correctly. Instead, these values are just used to help you navigate your experiments while digging into analyses. However, we may later use these values to re-score outputs or fine-tune your models
		 */
		expected?: {
			[k: string]: unknown
		}
		/**
		 * The error that occurred, if any.
		 */
		error?: {
			[k: string]: unknown
		}
		/**
		 * A dictionary of numeric values (between 0 and 1) to log. The scores should give you a variety of signals that help you determine how accurate the outputs are compared to what you expect and diagnose failures. For example, a summarization app might have one score that tells you how accurate the summary is, and another that measures the word similarity between the generated and grouth truth summary. The word similarity score could help you determine whether the summarization was covering similar concepts or not. You can use these scores to help you sort, filter, and compare experiments
		 */
		scores?: {
			[k: string]: number
		}
		/**
		 * A dictionary with additional data about the test example, model outputs, or just about anything else that's relevant, that you can use to help find and analyze examples later. For example, you could log the `prompt`, example's `id`, or anything else that would be useful to slice/dice later. The values in `metadata` can be any JSON-serializable type, but its keys must be strings
		 */
		metadata?: {
			[k: string]: {
				[k: string]: unknown
			}
		}
		/**
		 * A list of tags to log
		 */
		tags?: string[]
		/**
		 * Metrics are numerical measurements tracking the execution of the code that produced the experiment event. Use "start" and "end" to track the time span over which the experiment event was produced
		 */
		metrics?: {
			/**
			 * A unix timestamp recording when the section of code which produced the experiment event started
			 */
			start?: number
			/**
			 * A unix timestamp recording when the section of code which produced the experiment event finished
			 */
			end?: number
			/**
			 * The number of tokens in the prompt used to generate the experiment event (only set if this is an LLM span)
			 */
			prompt_tokens?: number
			/**
			 * The number of tokens in the completion generated by the model (only set if this is an LLM span)
			 */
			completion_tokens?: number
			/**
			 * The total number of tokens in the input and output of the experiment event.
			 */
			tokens?: number
			/**
			 * This metric is deprecated
			 */
			caller_functionname?: {
				[k: string]: unknown
			}
			/**
			 * This metric is deprecated
			 */
			caller_filename?: {
				[k: string]: unknown
			}
			/**
			 * This metric is deprecated
			 */
			caller_lineno?: {
				[k: string]: unknown
			}
		}
		/**
		 * Context is additional information about the code that produced the experiment event. It is essentially the textual counterpart to `metrics`. Use the `caller_*` attributes to track the location in code which produced the experiment event
		 */
		context?: {
			/**
			 * The function in code which created the experiment event
			 */
			caller_functionname?: string
			/**
			 * Name of the file in code where the experiment event was created
			 */
			caller_filename?: string
			/**
			 * Line of code where the experiment event was created
			 */
			caller_lineno?: number
		}
		/**
		 * A unique identifier used to link different experiment events together as part of a full trace. See the [tracing guide](https://www.braintrust.dev/docs/guides/tracing) for full details on tracing
		 */
		span_id: string
		/**
		 * An array of the parent `span_ids` of this experiment event. This should be empty for the root span of a trace, and should most often contain just one parent element for subspans
		 */
		span_parents?: string[]
		/**
		 * A unique identifier for the trace this experiment event belongs to
		 */
		root_span_id: string
		/**
		 * Human-identifying attributes of the span, such as name, type, etc.
		 */
		span_attributes?: {
			/**
			 * Name of the span, for display purposes only
			 */
			name?: string
			/**
			 * Type of the span, for display purposes only
			 */
			type?: "llm" | "score" | "function" | "eval" | "task" | "tool" | null
		}
		/**
		 * Whether this span is a root span
		 */
		is_root?: boolean
		/**
		 * Indicates the event was copied from another object.
		 */
		origin?: {
			/**
			 * Type of the object the event is originating from.
			 */
			object_type:
				| ("experiment" | "dataset" | "prompt" | "function" | "prompt_session")
				| "project_logs"
			/**
			 * ID of the object the event is originating from.
			 */
			object_id: string
			/**
			 * ID of the original event.
			 */
			id: string
			/**
			 * Transaction ID of the original event.
			 */
			_xact_id: string
		}
	}[]
	/**
	 * Pagination cursor
	 *
	 * Pass this string directly as the `cursor` param to your next fetch request to get the next page of results. Not provided if the returned result set is empty.
	 */
	cursor?: string
}

const buildSpanTree = (events: Response["events"]) => {
	// Create a map of root spans to their subspans
	const rootSpanMap: Record<string, Response["events"]> = {}

	// First, identify all root spans and initialize their arrays
	const rootSpans = events.filter((e) => e.is_root)
	rootSpans.forEach((rootSpan) => {
		rootSpanMap[rootSpan.span_id] = [rootSpan]
	})

	// Then process non-root spans
	const nonRootSpans = events.filter((e) => !e.is_root)
	nonRootSpans.forEach((span) => {
		// Each span should have a root_span_id that tells us which root it belongs to
		if (span.root_span_id && rootSpanMap[span.root_span_id]) {
			rootSpanMap[span.root_span_id].push(span)
		}
	})

	return rootSpanMap
}

const getLastLlmSpans = (spanTree: Record<string, Response["events"]>) => {
	const lastLlmSpans: Record<string, Response["events"][0] | undefined> = {}

	for (const [rootSpanId, spans] of Object.entries(spanTree)) {
		// Filter for LLM spans and sort by timestamp (assuming newer spans have higher timestamps)
		const llmSpans = spans
			.filter((span) => span.span_attributes?.type === "llm")
			.sort((a, b) => {
				const aTime = a.metrics?.end || 0
				const bTime = b.metrics?.end || 0
				return bTime - aTime // Sort in descending order (newest first)
			})

		lastLlmSpans[rootSpanId] = llmSpans[0] // Get the first one (latest) or undefined if no LLM spans
	}

	return lastLlmSpans
}

interface TrainingExample {
	id: string // root span id
	input: string
	messages: ChatCompletionMessageParam[]
	tools?: ChatCompletionTool[]
}

const createTrainingDataset = (
	rootSpanMap: Record<string, Response["events"]>,
	lastLlmSpans: Record<string, Response["events"][0] | undefined>,
): TrainingExample[] => {
	const dataset: TrainingExample[] = []

	for (const [rootSpanId, llmSpan] of Object.entries(lastLlmSpans)) {
		if (!llmSpan || !llmSpan.input || !llmSpan.output) continue

		const rootSpan = rootSpanMap[rootSpanId][0]
		const expected = rootSpan.expected

		if (!expected) continue

		try {
			// Get all messages
			const messages: TrainingExample["messages"] = [
				...(llmSpan.input as ChatCompletionMessageParam[]),
				(llmSpan.output as unknown as ChatCompletion["choices"])[0].message,
			]
			// Find index of first registry_upsert_entry call
			const firstUpsertIndex = messages.findIndex(
				(msg) =>
					msg.role === "assistant" &&
					msg.tool_calls?.some(
						(call) => call.function?.name === "registry_upsert_entry",
					),
			)

			if (firstUpsertIndex === -1) {
				console.warn(
					`Skipping example without registry_upsert_entry call: ${rootSpanId}`,
				)
				continue
			}

			// Trim to first registry_upsert_entry call
			const trimmedMessages: ChatCompletionMessageParam[] = messages
				.slice(0, firstUpsertIndex + 1)
				.map((msg) => ({
					...msg,
					// Old OpenAI format required for fine-tuning
					role: msg.role === "developer" ? "system" : msg.role,
					// Flatten content into string
					content: Array.isArray(msg.content)
						? msg.content
								.map((part) => part.type === "text" && part.text)
								.join("")
						: msg.content,
				}))
				.map(
					(msg) =>
						omitBy(
							pick(msg, ["role", "content", "tool_calls", "tool_call_id"]),
							isNil,
						) as unknown as ChatCompletionMessageParam,
				)

			// Overwrite the registry_upsert_entry with expected output
			const lastMsg = trimmedMessages[trimmedMessages.length - 1]
			if (lastMsg.role === "assistant" && lastMsg.tool_calls) {
				// biome-ignore lint/performance/noDelete: We can't have undefined
				delete lastMsg.content
				lastMsg.tool_calls[0].function.arguments = JSON.stringify({
					servers: expected,
				})
			}

			const tools = (llmSpan.metadata?.tools as unknown as ChatCompletionTool[])
				// Remove "strict" paramter from all tool calls
				.map((tool) => ({
					...tool,
					function: {
						...omit(tool.function, ["strict"]),
					},
				}))

			const example: TrainingExample = {
				id: rootSpanId,
				input: rootSpan.input as unknown as string,
				messages: trimmedMessages,
				tools,
			}

			dataset.push(example)
		} catch (error) {
			console.error(`Error processing span ${rootSpanId}:`, error)
		}
	}

	return dataset
}

/**
 * Pulls the full trace from a Braintrust experiment.
 */
async function main() {
	const argv = await yargs(hideBin(process.argv))
		.option("experimentId", {
			alias: "e",
			type: "string",
			description: "Braintrust experiment ID to fetch data from",
			demandOption: true,
		})
		.help().argv

	dotenv.config({ path: ".env.development.local" })

	const resp = await fetch(
		`https://api.braintrust.dev/v1/experiment/${argv.experimentId}/fetch`,
		{
			headers: {
				Authorization: `Bearer ${process.env.BRAINTRUST_API_KEY}`,
			},
		},
	)
	const data: Response = await resp.json()

	const spanTree = buildSpanTree(data.events)
	const lastLlmSpans = getLastLlmSpans(spanTree)
	console.log(`Found ${Object.keys(spanTree).length} root spans`)
	console.log(
		`Found ${Object.values(lastLlmSpans).filter(Boolean).length} root spans with LLM spans`,
	)

	const trainingDataset = createTrainingDataset(spanTree, lastLlmSpans)
	console.log(`Created ${trainingDataset.length} training examples`)

	// Push to Braintrust
	const dataset = initDataset("Smithery", { dataset: "crawl_ft_dataset" })

	for (const example of trainingDataset) {
		const id = dataset.insert({
			id: example.input,
			input: example.input,
			expected: example.messages,
		})
		console.log("Inserted record with id", id)
	}

	console.log(await dataset.summarize())

	// Push dataset to JSONL file
	// TODO: Make this general purpose "Braintrust" -> FT script
	const outputPath = path.join("scratch", "crawl_ft_dataset.jsonl")

	fs.writeFileSync(
		outputPath,
		trainingDataset
			.map((example) => JSON.stringify(pick(example, ["messages", "tools"])))
			.join("\n"),
	)

	console.log(`Dumped ${trainingDataset.length} examples to ${outputPath}`)
}

main()
